{{- if .Values.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argo-diff.secretName" . }}
  namespace: {{ include "argo-diff.namespace" . }}
  labels:
    {{- include "argo-diff.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
{{- with .Values.config }}
{{- if or .argocd.authToken .github.application.privateKey .github.auth.token .github.webhook.sharedSecret }}
data:
  {{- with .argocd.authToken }}
  ARGOCD_AUTH_TOKEN: {{ . | b64enc }}
  {{- end }}
  {{- with .github.application.privateKey }}
  GITHUB_APP_PRIVATE_KEY: {{ . | b64enc }}
  {{- end }}
  {{- with .github.webhook.sharedSecret }}
  GITHUB_WEBHOOK_SECRET: {{ . | b64enc }}
  {{- end }}
  {{- with .github.auth.token }}
  GITHUB_TOKEN: {{ . | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
